export const practiceAreas = [
  "Aile ve Boşanma Hukuku",
  "Birleşme ve Devralmalar",
  "Ceza Hukuku",
  "Enerji Hukuku",
  "Fikri ve Sınai Mülkiyet Hukuku",
  "İcra ve İflas Hukuku",
  "İdare ve Vergi Hukuku",
  "İnşaat ve Gayrimenkul Hukuku",
  "İnşaat ve İmar Hukuku",
  "İş ve Sosyal Güvenlik Hukuku",
  "Kira Hukuku",
  "Kişisel Verilerin Korunması Hukuku",
  "Miras Hukuku",
  "Rekabet Hukuku",
  "Sağlık ve İlaç Hukuku",
  "Sigorta Hukuku",
  "Spor Hukuku",
  "Sözleşmeler Hukuku",
  "Şirketler ve Ticaret Hukuku",
  "Taşımacılık ve Lojistik Hukuku",
  "Tüketici Hukuku",
  "Yabancılar ve Vatandaşlık Hukuku",
];

export const practiceAreaPages = [
  {
    title: "Aile ve Boşanma Hukuku",
    slug: "aile-ve-bosanma-hukuku",
    paragraphs: [
      "Büromuz, taraflar arasında ortaya çıkabilecek uyuşmazlıkların hukuki zeminde doğru ve etkin bir şekilde değerlendirilmesi amacıyla kapsamlı danışmanlık hizmeti sunmaktadır.",
      "Bu kapsamda; boşanma süreci, mal rejiminin tasfiyesi, nafaka ve tazminat talepleri, velayet düzenlemeleri, soy bağına ilişkin işlemler, evlilik sözleşmelerinin hazırlanması ve aile içi koruma tedbirleri gibi konularda müvekkillere mevcut hukuki durumun analizi yapılarak profesyonel yönlendirme sağlanmaktadır.",
      "Süreçlerin her aşamasında, somut olayın özelliklerine uygun şekilde tarafların hak ve yükümlülükleri belirlenmekte; olası riskler değerlendirilmekte ve yürürlükteki mevzuata uygun çözüm alternatifleri geliştirilmektedir. Ayrıca, yabancı mahkeme kararlarının tanınması ve tenfizi ile uluslararası aile hukuku kapsamında ortaya çıkan uyuşmazlıklara ilişkin de danışmanlık hizmeti verilmektedir. Aile ilişkilerini doğrudan etkileyen bir alan olduğu bilinciyle; süreçlerin hassasiyetle yürütülmesine özen göstererek müvekkillerin hem hukuki güvenliğini hem de aile içi dengelerini gözeten çözümler üretmekteyiz. Güncel mevzuat ve yerleşik yargı içtihatları doğrultusunda, sistematik, şeffaf ve çözüm odaklı bir kurumsal yaklaşım çerçevesinde yürütülmekte; müvekkillerin süreci doğru, etkin ve güvenli bir şekilde yönetebilmesini hedeflemekteyiz.",
    ],
  },
  {
    title: "Birleşme ve Devralmalar",
    detailTitle: "Birleşme ve Devralmalar Hukuku",
    slug: "birlesme-ve-devralmalar",
    paragraphs: [
      "Büromuz, yerli ve yabancı müvekkillere geniş bir sektör yelpazesinde kapsamlı ve stratejik hukuki danışmanlık hizmetleri sunmaktadır. Hisse ve varlık devirleri, şirket birleşmeleri, bölünmeler, ortak girişimler ve yeniden yapılandırma işlemleri dahil olmak üzere, işlemlerin tüm aşamalarında müvekkillerimizin ticari hedefleriyle uyumlu, pratik ve sonuç odaklı çözümler geliştirmekteyiz.",
      "İşlem öncesi hazırlık süreçlerinden başlayarak; gizlilik sözleşmeleri ve niyet mektuplarının hazırlanması, kapsamlı hukuki inceleme çalışmalarının yürütülmesi, risk analizi ve yapılandırma süreçlerinin kurgulanması, pay devir ve hissedarlık sözleşmeleri başta olmak üzere tüm işlem dokümantasyonunun hazırlanması ve müzakeresi konularında destek sağlamaktayız. Aynı zamanda gerekli idari izin ve onayların alınması, düzenleyici kurumlar nezdindeki başvuru ve bildirim süreçlerinin yürütülmesi ile kapanış işlemlerinin eksiksiz şekilde tamamlanmasını temin etmekteyiz.",
      "Büromuz, birleşme ve devralma işlemlerinde yalnızca hukuki değil; finansal, vergisel ve operasyonel boyutları da dikkate alan bütüncül bir yaklaşım benimsemekte olup, işlem sonrası entegrasyon, kurumsal yapılandırma ve yönetişim süreçlerinde de müvekkillerine danışmanlık sunmaktadır. Ayrıca birleşme ve devralmalardan kaynaklanan uyuşmazlıkların çözümünde mahkemeler ve tahkim mercileri nezdinde etkin temsil hizmeti vermekteyiz.",
      "Çok disiplinli yaklaşımımız ve sınır ötesi işlemlerdeki deneyimimiz sayesinde, hem alıcı hem de satıcı taraf için sürecin her aşamasında güvenilir, hızlı ve sürdürülebilir çözümler sunarak müvekkillerin menfaatlerini en üst düzeyde korumayı hedeflemekteyiz.",
    ],
  },
  {
    title: "Ceza Hukuku",
    slug: "ceza-hukuku",
    paragraphs: [
      "Soruşturma, kovuşturma, istinaf ve temyiz süreçlerinin tamamında müvekkillerine hukuki destek sunmaktadır.",
      "Her dosyaya özel yaklaşım benimseyen büromuz, sürecin tüm aşamalarını titizlikle takip ederek etkin ve sonuç odaklı temsil sağlamaktadır. Ceza yargılaması kapsamında; şikâyet ve suç duyurusu süreçleri, savcılık ve mahkeme işlemleri, tutukluluk ve tahliye başvuruları, koruma tedbirlerine itirazlar ile üst yargı mercilerine yapılacak başvurular profesyonel şekilde yürütülmektedir. Ağır ceza ve asliye ceza davaları başta olmak üzere; bilişim suçları, dolandırıcılık, yaralama, tehdit ve hakaret gibi tüm ceza hukuku alanlarında hizmet verilmektedir.",
      "Mesleki etik ilkelere bağlı, şeffaf ve müvekkil odaklı yaklaşımımızla, güncel mevzuat ve yargı içtihatlarını yakından takip ederek güvenilir ve etkin çözümler sunmaktayız. Ceza yargılamasının tüm aşamalarında ve tazminat davalarında müvekkillerin haklarını en güçlü şekilde korumayı hedeflemekteyiz.",
    ],
  },
  {
    title: "Enerji Hukuku",
    slug: "enerji-hukuku",
    paragraphs: [
      "Büromuz, sektörde faaliyet gösteren yerli ve yabancı müvekkiller ile enerji üreticileri, dağıtım ve iletim şirketleri, yatırımcılar, finans kuruluşları ve hizmet sağlayıcılar dahil olmak üzere sektörün tüm paydaşlarına, ihale ve lisans süreçlerinden proje geliştirme, işletme ve sona erdirme aşamalarına kadar geniş bir yelpazede destek vermektedir.",
      "Enerji hukukundaki derin bilgi birikimimiz ve sektörel deneyimimiz sayesinde; elektrik, doğalgaz, petrol ve yenilenebilir enerji alanlarında gerçekleştirilen yatırımlara ilişkin lisanslandırma, düzenleyici uyum, sözleşme hazırlığı, proje finansmanı ve birleşme-devralma işlemlerinde müvekkillere etkin çözümler sunmaktayız. Özellikle güneş ve rüzgâr enerjisi projeleri ile elektrikli araç şarj altyapısı alanlarında, yerli ve yabancı yatırımcılara yönelik kapsamlı danışmanlık hizmeti sağlamaktayız.",
      "Büromuz; EPDK başta olmak üzere ilgili idari otoriteler nezdindeki tüm başvuru ve izin süreçlerinin yürütülmesi, teşvik mekanizmalarının değerlendirilmesi, enerji alım-satım sözleşmeleri, EPC ve O&M sözleşmeleri ile proje belgelerinin hazırlanması ve müzakeresi konularında aktif rol almaktadır. Bunun yanı sıra, enerji projelerine ilişkin uyuşmazlıkların çözümünde idari merciler, mahkemeler ve tahkim süreçlerinde müvekkilleri temsil etmekteyiz.",
      "Enerji ve doğal kaynaklar alanındaki hizmetlerimiz; petrol ve doğalgaz projeleri, boru hatları, LNG, rafineri ve petrokimya yatırımları, madencilik faaliyetleri ile hidroelektrik, güneş, rüzgâr ve jeotermal gibi yenilenebilir enerji projelerini kapsamaktadır. Proje geliştirme aşamasından finansman ve işletme süreçlerine kadar tüm değer zincirine hâkimiyetimiz, müvekkillere sürdürülebilir ve uygulanabilir hukuki çözümler sunmamızı sağlamaktadır.",
      "Kamu-özel iş birliği (KÖİ), yap-işlet-devret (YİD) ve özelleştirme projelerinde edindiğimiz tecrübe ile ihale süreçlerinden sözleşme müzakerelerine ve uygulama aşamasına kadar müvekkillere rehberlik etmekteyiz. Uluslararası projelerde ise farklı hukuk sistemleri arasındaki uyumu sağlayarak sınır ötesi işlemlerde etkin destek sunmaktayız.",
      "Sürekli değişen mevzuat ve piyasa koşullarını yakından takip eden ekibimiz, müvekkillerine yalnızca hukuki değil aynı zamanda ticari açıdan da uygulanabilir, stratejik çözümler sunmayı hedeflemektedir. Enerji sektöründe karşılaşılan karmaşık süreçleri etkin şekilde yöneterek, yatırımcıların fırsatları değerlendirmesine ve riskleri minimize etmesine katkı sağlamaktayız.",
      "Kapsamlı ve çözüm odaklı hukuki danışmanlık hizmetleri sunmaktayız. Enerji yatırımlarının her aşamasında; ihale ve teklif süreçlerinden lisanslandırma ve izinlere, proje geliştirme, finansman, işletme ve sona erdirme süreçlerine kadar geniş bir yelpazede destek sağlamaktayız.",
    ],
  },
  {
    title: "Fikri ve Sınai Mülkiyet Hukuku",
    slug: "fikri-ve-sinai-mulkiyet-hukuku",
    paragraphs: [
      "Büromuz, marka, patent, faydalı model, endüstriyel tasarım, telif hakları, coğrafi işaretler, internet alan adları, ticari sırlar ve ilgili tüm sınai hakları kapsayan geniş bir uzmanlık alanında yerli ve yabancı müvekkillere kapsamlı hukuki danışmanlık ve dava hizmeti sunmaktadır.",
      "Bu kapsamda müvekkillere, fikri mülkiyet haklarının oluşturulması, korunması, yönetimi, tescili ve tescil sonrası süreçlerinin takibi konularında stratejik destek sağlanmakta; Türk Patent ve Marka Kurumu, Dünya Fikri Mülkiyet Örgütü (WIPO), uluslararası tescil sistemleri (Madrid Protokolü, PCT, Lahey Sistemi) ve ilgili tüm idari ve yargısal merciler nezdinde temsil hizmeti verilmektedir.",
      "Hizmetlerimiz; marka ve patent araştırmaları, başvuru ve tescil süreçlerinin yürütülmesi, itirazların hazırlanması ve savunulması, hükümsüzlük ve iptal davaları, ihlal ve tecavüz davaları, haksız rekabet uyuşmazlıkları ile ihtiyati tedbir ve tazminat talepli davaların takibini kapsamaktadır. Ayrıca taklit ve korsan ürünlerle mücadele kapsamında piyasa gözetimi, delil toplama, gümrüklerde el koyma işlemleri, baskın ve operasyon süreçlerinin yürütülmesi ile ceza ve hukuk yargılamalarında etkin temsil sağlanmaktadır.",
      "Fikri mülkiyet haklarının ticarileştirilmesi kapsamında; lisans, devir, temlik, franchise, ortak girişim, dağıtım, sponsorluk ve know-how sözleşmeleri ile yazılım, teknoloji transferi, reklam, medya, yapımcılık ve bilişim sözleşmeleri dahil olmak üzere her türlü sözleşmenin hazırlanması, müzakeresi ve uygulanması süreçlerinde hukuki destek verilmektedir. Ayrıca gizlilik sözleşmeleri, ticari sırların korunması, veri güvenliği ve çalışan buluşlarına ilişkin süreçler de uzmanlık alanımız içerisindedir.",
      "Dijitalleşme ve teknoloji odaklı gelişmeler doğrultusunda; e-ticaret, yazılım, yapay zeka, blockchain, oyun, medya ve telekomünikasyon alanlarında faaliyet gösteren müvekkillere özel çözümler sunulmakta, internet ortamında gerçekleşen hak ihlalleri, alan adı uyuşmazlıkları ve çevrimiçi marka koruması konularında etkin hukuki koruma sağlanmaktadır. Alan adı ihtilaflarında WIPO ve TRABİS başta olmak üzere ulusal ve uluslararası uyuşmazlık çözüm mekanizmalarında temsil hizmeti verilmektedir.",
      "Ayrıca telif hakkı kapsamındaki eserlerin korunması, lisanslanması ve yönetimi; müzik, film, yayıncılık, yazılım, dijital içerik ve sanat eserlerine ilişkin tüm hakların korunması; sanatçı, yapımcı, senarist, yayıncı ve içerik üreticilerine yönelik sözleşmelerin hazırlanması ve uyuşmazlıkların çözümü konularında da kapsamlı danışmanlık sağlanmaktadır. Reklam, medya ve eğlence hukuku alanında ise içerik üretimi, yayıncılık ve dijital pazarlama faaliyetlerine ilişkin hukuki uyum süreçleri yürütülmektedir.",
      "Patent alanında; buluşların korunması, patentlenebilirlik analizleri, PCT başvuruları, ulusal ve uluslararası tescil süreçleri, lisanslama ve teknoloji transferi işlemleri ile patent ihlali ve hükümsüzlük davaları titizlikle yönetilmektedir. Endüstriyel tasarımlar ve faydalı modeller bakımından da tescil, koruma, ihlal ve iptal süreçlerinde etkin hukuki destek sunulmaktadır.",
      "Coğrafi işaretler ve geleneksel ürün adları kapsamında; tescil başvuruları, koruma stratejileri, itiraz süreçleri ve ihlal davaları yürütülmekte; yerel değerlerin ulusal ve uluslararası düzeyde korunması sağlanmaktadır. Islahçı hakları alanında ise bitki çeşitlerinin tescili, korunması, lisanslanması ve ilgili uyuşmazlıkların çözümü konularında destek verilmektedir.",
      "Fikri mülkiyet portföy yönetimi kapsamında müvekkillerin tüm fikri varlıklarının stratejik olarak yönetilmesi, değerinin artırılması, risk analizlerinin yapılması ve ticari hedeflerle uyumlu şekilde yapılandırılması sağlanmaktadır. Bu çerçevede düzenli portföy denetimleri, durum tespit çalışmaları ve stratejik danışmanlık hizmetleri sunulmaktadır.",
    ],
  },
  {
    title: "İcra ve İflas Hukuku",
    slug: "icra-ve-iflas-hukuku",
    paragraphs: [
      "Büromuz, yerli ve yabancı müvekkillerine alacak tahsili, borç yönetimi ve finansal yeniden yapılandırma süreçlerinin tüm aşamalarında kapsamlı hukuki danışmanlık ve avukatlık hizmetleri sunmaktadır. İcra takiplerinin başlatılması ve yürütülmesi, kambiyo senetlerine dayalı takipler, ilamsız icra işlemleri, ipoteğin paraya çevrilmesi ve tahliye süreçleri dâhil olmak üzere tüm cebri icra yollarının etkin şekilde yönetilmesini sağlamaktayız.",
      "Alacakların tahsili sürecinde borçlulara ait malvarlığının araştırılması, haciz ve satış işlemlerinin yürütülmesi ile icra müdürlükleri ve mahkemeleri nezdindeki tüm uyuşmazlıkların takibi tarafımızca gerçekleştirilmektedir. Ayrıca borçlu ve alacaklı taraflar arasında sulh görüşmeleri yürütülmesi, borç yapılandırma anlaşmalarının hazırlanması ve icra süreçlerine ilişkin risklerin yönetilmesi konularında stratejik çözümler sunmaktayız.",
      "İflas ve konkordato süreçlerinde; başvuru aşamasından mühlet süreçlerinin yönetimine, konkordato projelerinin hazırlanmasından alacaklı müzakerelerine kadar tüm süreçlerde etkin hukuki destek sağlanmaktadır. Finansal zorluk yaşayan şirketler için borçların yeniden yapılandırılması, alacaklılarla müzakere edilmesi ve sürdürülebilir finansal yapıların oluşturulmasına yönelik çözümler geliştirilmektedir.",
      "İflas süreçlerinde hem alacaklı hem de borçlu tarafı temsil ederek tasfiye, iflas masası işlemleri ve sınır ötesi iflas uygulamalarında kapsamlı hukuki hizmet sunmaktayız. Uluslararası alacak tahsili süreçlerinde ise yabancı hukuk büroları ile koordinasyon sağlanarak çok yargı alanlı uyuşmazlıkların etkin şekilde yönetilmesi sağlanmaktadır.",
      "Tüm bu süreçlerde amacımız; müvekkillerin alacaklarına en hızlı ve etkin şekilde kavuşmalarını sağlamak, borç ilişkilerinin hukuka uygun biçimde yeniden yapılandırılmasını temin etmek ve finansal risklerin etkin biçimde yönetilmesine katkıda bulunmaktır.",
    ],
  },
  {
    title: "İdare ve Vergi Hukuku",
    slug: "idare-ve-vergi-hukuku",
    paragraphs: [
      "Büromuz, gerçek ve tüzel kişilere kamu kurumları ile yürütülen tüm işlemler ve uyuşmazlıklarda kapsamlı hukuki danışmanlık ve dava takibi hizmeti sunmaktadır.",
      "Müvekkillerin idari makamlar ve düzenleyici otoriteler nezdindeki süreçlerinde hak kaybı yaşamamaları için, her aşamada stratejik ve çözüm odaklı bir yaklaşım benimsenmektedir.",
      "İdare hukuku kapsamında, idari işlemlerin iptali ve tam yargı davalarının yürütülmesi, idari para cezalarına karşı itiraz süreçleri, ruhsat, izin ve lisans işlemleri ile gümrük ve kamu ihale mevzuatından doğan uyuşmazlıkların çözümü konularında müvekkiller temsil edilmektedir. Ayrıca Rekabet Kurumu, BDDK, EPDK ve SPK gibi düzenleyici ve denetleyici otoriteler nezdindeki işlemler de büromuz tarafından etkin şekilde takip edilmektedir.",
      "Vergi hukuku alanında ise vergi planlaması, vergi incelemeleri sırasında hukuki destek, vergi tarhiyat ve cezalarına karşı itiraz ve dava süreçleri ile uzlaşma mekanizmalarının yürütülmesi konularında hizmet verilmektedir. Bunun yanında vergi iadesi, teşvik ve muafiyet süreçleri ile gümrük vergilerinden ve vergi suçlarından doğan uyuşmazlıklar da kapsamlı şekilde ele alınmaktadır.",
      "Büromuz ayrıca transfer fiyatlandırması, örtülü sermaye, birleşme ve devralmaların vergisel boyutu ile uluslararası vergi yapılandırmaları gibi karmaşık alanlarda da danışmanlık sunmakta; şirketlerin vergisel risklerini azaltmaya ve mevzuata uyumlu şekilde yapılandırılmasına katkı sağlamaktadır.",
    ],
  },
  {
    title: "İnşaat ve İmar Hukuku",
    detailTitle: "İmar Hukuku",
    slug: "insaat-ve-imar-hukuku",
    paragraphs: [
      "Büromuz, yerli ve yabancı müvekkillere kapsamlı, stratejik ve çözüm odaklı hukuki danışmanlık ve dava takip hizmetleri sunmaktadır. İmar planlamasından yapılaşma süreçlerine kadar uzanan geniş bir yelpazede, müvekkillerin hukuki risklerini en aza indirmeyi ve yatırımlarını mevzuata tam uyumlu şekilde gerçekleştirmelerini sağlamayı amaçlıyoruz.",
      "Bu kapsamda; nazım ve uygulama imar planlarının hazırlanması, incelenmesi ve hukuka uygunluğunun değerlendirilmesi, plan değişiklikleri ile ilgili süreçlerin yönetimi ve gerekli itirazların yapılması konularında etkin danışmanlık sağlamaktayız. Belediyeler ve diğer idari kurumlar nezdinde yürütülen işlemlerde müvekkilleri temsil ederek imar planlarına ilişkin doğabilecek uyuşmazlıkların önlenmesi ve çözülmesi için proaktif bir yaklaşım benimsiyoruz.",
      "İmar planlarının iptali ve yürütmenin durdurulması davaları başta olmak üzere, parselasyon, ifraz ve tevhit işlemlerinden kaynaklanan uyuşmazlıklar, yapı ruhsatı ve yapı kullanma izin belgelerine ilişkin ihtilaflar ile imar para cezalarına karşı açılacak davalarda müvekkillere etkin hukuki temsil sunmaktayız. İdari işlemlerin iptali ve bu işlemlerden doğan zararların tazmini amacıyla açılan davalarda, süreci titizlikle yönetmekteyiz.",
      "Ruhsatsız veya ruhsata aykırı yapılaşmalar, yıkım kararları, yapı tatil tutanakları ve imar kirliliğine ilişkin işlemler kapsamında müvekkillere hukuki destek sağlamakta; bu tür yaptırımlara karşı başvuru ve dava süreçlerini yürütmekteyiz. Aynı zamanda yapı ruhsatı alınması, yapı kullanım izin belgesi (iskan) süreçlerinin tamamlanması ve gerekli idari başvuruların yapılması aşamalarında müvekkillere rehberlik ediyoruz.",
      "Kentsel dönüşüm, kamulaştırma ve kamulaştırmasız el atma süreçlerinde; hak sahiplerinin menfaatlerinin korunması, uzlaşma görüşmelerinin yürütülmesi ve gerektiğinde dava yoluna başvurulması konularında kapsamlı hizmet sunmaktayız. Ayrıca imar değişikliklerinden kaynaklanan değer kayıpları ve zararlara ilişkin tazminat davalarında da müvekkillerin haklarını etkin şekilde savunuyoruz.",
      "Türkiye’nin inşaat sektöründe faaliyet gösteren en önemli şirketlerinden yatırım bankalarına, gayrimenkul fonlarından bireysel yatırımcılara kadar gayrimenkul yatırımcılarının özel ihtiyaçlarına yönelik hizmetler veriyoruz.",
    ],
  },
  {
    title: "İnşaat ve Gayrimenkul Hukuku",
    slug: "insaat-ve-gayrimenkul-hukuku",
    paragraphs: [
      "Büromuz, gayrimenkul geliştiricilerinden yatırım bankalarına, fonlardan bireysel yatırımcılara, yüklenici ve taşeronlardan kamu kurumlarına kadar geniş bir müvekkil portföyüne hizmet sunmaktadır. Her bir projenin kendine özgü ihtiyaçlarını analiz ederek, bu doğrultuda özelleştirilmiş ve sürdürülebilir hukuki çözümler üretmektedir. Türkiye’de ve uluslararası ölçekte faaliyet gösteren inşaat, altyapı, alışveriş merkezi yönetimi, turizm ve gayrimenkul danışmanlığı sektörlerindeki şirketlere danışmanlık verilmekte; aynı zamanda uyuşmazlık çözüm süreçleri etkin şekilde yönetilmektedir.",
      "Büromuz, küçük, orta ve büyük ölçekli; konut, ticari, endüstriyel, turizm, karma kullanım ve altyapı projelerinin tüm aşamalarında hukuki destek sağlamaktadır. Bu kapsamda; hukuki inceleme süreçlerinden proje geliştirme ve planlamaya, finansman ve teminat yapılandırmalarından ruhsatlandırma ve imar süreçlerine, sözleşme hazırlama ve müzakerelerinden uygulama ve yönetim aşamalarına kadar geniş bir yelpazede danışmanlık sunulmaktadır.",
      "Özellikle; kat karşılığı inşaat ve gelir paylaşımı sözleşmeleri, anahtar teslim ve EPC sözleşmeleri, FIDIC sözleşmeleri, taşeronluk ve tedarik sözleşmeleri, kira ve satış sözleşmeleri, yönetim planları ile ortak girişim ve proje finansmanı sözleşmeleri gibi karmaşık yapıdaki hukuki metinlerin hazırlanması ve müzakere edilmesinde önemli deneyime sahibiz. İnşaat projelerinin çok katmanlı yapısı, risk paylaşımı ve uluslararası unsurlar içermesi sebebiyle, sözleşme yönetimi süreçleri titizlikle yürütülmektedir.",
      "Gayrimenkul işlemleri kapsamında; taşınmaz alım-satımı, kiralama, finansman, ipotek tesisi, ayni ve şahsi hakların kurulması, tapu ve kadastro işlemlerinin takibi, yabancıların Türkiye’de gayrimenkul edinimi ve yatırım süreçlerinin yönetimi konularında müvekkillere kapsamlı destek sağlanmaktadır. Ayrıca gayrimenkul yatırım fonları ve şirketlerinin yapılandırılması, portföy yönetimi ve finansman süreçlerine ilişkin hukuki danışmanlık hizmetleri de sunulmaktadır.",
      "Gayrimenkul Hukuku alanında müvekkillere geniş bir yelpazede hukuki hizmetler sunmaktayız. Satış, kiralama, inşaat sözleşmeleri, tapu işlemleri, kamulaştırma, gayrimenkul projelerinin hukuki denetimi gibi konularda uzmanlaşmış ekibimizle müvekkillerin her türlü gayrimenkul işlemini güvenle gerçekleştirmelerine yardımcı olmaktayız. Ayrıca, gayrimenkul alım-satım sözleşmeleri, kira sözleşmeleri ve kat mülkiyeti gibi pek çok alanda danışmanlık sağlıyor; taraflar arasındaki uyuşmazlıkların çözümünde etkin bir şekilde yer alıyoruz.",
      "İmar ve planlama boyutunda ise; imar planlarının hazırlanması, değiştirilmesi ve uygulanması, ruhsat ve izin süreçlerinin yürütülmesi, kentsel dönüşüm projeleri, çevresel etki değerlendirme süreçleri ve idari başvuruların takibi konularında müvekkillere rehberlik edilmektedir. İdari işlemlere karşı açılan iptal davaları, kamulaştırma ve kamulaştırmasız el atma davaları ile imar ve planlama kaynaklı uyuşmazlıklar da etkin şekilde takip edilmektedir.",
      "Uyuşmazlık çözümü alanında büromuz; adli yargı, idari yargı, tahkim ve arabuluculuk süreçlerinde güçlü bir temsil sunmaktadır. İnşaat projelerinden doğan gecikmeler, ayıplı işler, hakediş uyuşmazlıkları, sözleşme ihlalleri, kira ilişkileri ve mülkiyet ihtilafları gibi konularda müvekkillerin hak ve menfaatlerini en üst düzeyde korumayı hedeflemektedir.",
      "Büromuz ayrıca kamu ihale mevzuatı kapsamında gerçekleştirilen projelerde; ihale dokümanlarının hazırlanması, teklif süreçlerinin yönetimi, sözleşme uygulamalarında ortaya çıkan uyuşmazlıkların çözümü ve ilgili dava süreçlerinin takibi konularında da danışmanlık sağlamaktadır. Büyük ölçekli altyapı ve enerji projeleri ile kamu-özel iş birliği (PPP) ve proje finansmanı süreçlerinde edinilen deneyim, müvekkillere önemli avantajlar sunmaktadır.",
      "Disiplinler arası yaklaşımı benimseyen ekibimiz; finans, vergi, şirketler hukuku ve kamu hukuku alanlarındaki bilgi birikimini gayrimenkul ve inşaat hukuku ile entegre ederek bütüncül çözümler üretmektedir. Teknik uzmanlarla kurulan iş birlikleri sayesinde projelerin hem hukuki hem de teknik boyutları eş zamanlı olarak değerlendirilmektedir.",
      "Sonuç olarak büromuz; hızla değişen yerel ve küresel piyasa koşullarını yakından takip ederek, müvekkillerine yalnızca hukuki güvence sağlamakla kalmayıp aynı zamanda rekabet avantajı yaratan, uygulanabilir ve sürdürülebilir çözümler sunmayı ilke edinmiştir.",
    ],
  },
  {
    title: "İş ve Sosyal Güvenlik Hukuku",
    detailTitle: "İş Hukuku",
    slug: "is-ve-sosyal-guvenlik-hukuku",
    paragraphs: [
      "Büromuz, işverenlere ve kurumlara kapsamlı danışmanlık hizmetleri sunmaktadır.",
      "İş sözleşmelerinin hazırlanması ve sona erdirilmesi, işe alım ve işten çıkarma süreçlerinin yönetimi, işyeri politika ve prosedürlerinin oluşturulması gibi insan kaynakları süreçlerinin tüm aşamalarında müvekkillere destek sağlamaktayız.",
      "Bireysel ve toplu iş hukuku kapsamında; sendikalarla ilişkilerin yönetimi, toplu iş sözleşmelerinin müzakeresi, iş uyuşmazlıklarının çözümü ve arabuluculuk süreçlerinin yürütülmesi konularında stratejik ve sonuç odaklı çözümler geliştiriyoruz. İş kazaları, meslek hastalıkları, tazminat ve sosyal güvenlik süreçlerinde ise işverenlerin yasal yükümlülüklerini doğru ve eksiksiz şekilde yerine getirmelerine yardımcı oluyor; mevzuata tam uyumlu, pratik ve sonuç odaklı çözümler sunuyoruz. İş sağlığı ve güvenliği, iş yeri uyum programları, iç soruşturmalar ve etik süreçler dahil olmak üzere şirket içi düzenlemelerin kurulması ve geliştirilmesi konusunda danışmanlık vermekteyiz.",
      "Yeniden yapılanma, birleşme ve devralma süreçlerinin hukuka uygun ve etkin şekilde yürütülmesini sağlamaktayız. Ulusal ve uluslararası müvekkillere, yabancı çalışanların istihdamı süreçleri dahil olmak üzere geniş bir yelpazede hizmet sunan ekibimiz, mevzuata tam uyumlu, pratik ve sürdürülebilir çözümler üretmektedir.",
    ],
  },
  {
    title: "Kişisel Verilerin Korunması Hukuku",
    slug: "kisisel-verilerin-korunmasi-hukuku",
    paragraphs: [
      "Büromuz, müvekkillerine kapsamlı ve nitelikli hukuki danışmanlık hizmetleri sunmaktadır.",
      "Bu kapsamda; veri işleme faaliyetlerinin hukuka uygunluk sebepleri bakımından değerlendirilmesi, aydınlatma yükümlülüğü ve açık rıza süreçlerinin yapılandırılması, veri envanterlerinin hazırlanması, veri işleme amaç ve araçlarının hukuki analizi, veri minimizasyonu ve saklama sürelerinin belirlenmesi, saklama ve imha politikalarının oluşturulması ile veri güvenliğine ilişkin idari ve teknik tedbirlerin hukuki çerçevede kurgulanması konularında destek verilmektedir. Ayrıca, kişisel veri işleme faaliyetlerine ilişkin iç politika, prosedür ve uyum dokümantasyonunun hazırlanması ve güncellenmesi süreçleri yürütülmektedir.",
      "Müvekkillerin organizasyon yapıları ve sektörel faaliyetleri dikkate alınarak, veri sorumlusu yükümlülüklerinin tespiti yapılmakta; VERBİS kayıt ve bildirim süreçleri, veri sorumlusu–veri işleyen ilişkilerinin yapılandırılması, veri işleme sözleşmelerinin hazırlanması ve revizyonu ile yurt içi ve yurt dışı veri aktarım mekanizmalarının hukuka uygun şekilde kurulması sağlanmaktadır.",
      "Büromuz ayrıca, ilgili kişi başvurularının KVKK ve GDPR kapsamında değerlendirilmesi ve cevaplandırılması, veri ihlali yönetimi süreçlerinin yürütülmesi, Kişisel Verileri Koruma Kurumu ve diğer düzenleyici otoriteler nezdinde yürütülen inceleme ve soruşturmalarda temsil ve danışmanlık hizmeti verilmesi ile idari yaptırım süreçlerinin takibi konularında da hukuki destek sunmaktadır.",
      "Kişisel verilerin korunması hukukunun dinamik yapısı dikkate alınarak, müvekkillerin yalnızca mevzuata uyumunun sağlanması değil, aynı zamanda sürdürülebilir veri yönetişimi sistemlerinin kurulması hedeflenmektedir. Sunulan hizmetler, güncel mevzuat, yargı içtihatları ve düzenleyici otorite uygulamaları doğrultusunda, sistematik, denetlenebilir ve risk temelli bir kurumsal yaklaşım çerçevesinde yürütülmektedir.",
    ],
  },
  {
    title: "Kira Hukuku",
    slug: "kira-hukuku",
    paragraphs: [
      "Büromuz, kiraya verenlere ve kiracılara kapsamlı danışmanlık hizmetleri sunmaktadır. Kira sözleşmelerinin hazırlanması, incelenmesi ve sona erdirilmesi; kiralama süreçlerinin hukuka uygun şekilde yürütülmesi ile mevcut sözleşmelerin ihtiyaçlara göre düzenlenmesi ve güncellenmesi konularında müvekkillere destek sağlamaktayız.",
      "Bireysel ve kurumsal kira ilişkileri kapsamında; kira bedelinin belirlenmesi ve artırılması, kira tespit davaları, tahliye süreçleri ve kira alacaklarının tahsili gibi uyuşmazlıklarda stratejik ve sonuç odaklı çözümler üretmekteyiz. Kiracının tahliyesi, sözleşmeye aykırılık halleri ve ödeme yükümlülüklerinin ihlali gibi durumlarda hukuki sürecin doğru şekilde yönetilmesini sağlamaktayız.",
      "Ayrıca kira ilişkilerinden doğan uyuşmazlıklarda arabuluculuk süreçlerinin yürütülmesi, taraflar arasında uzlaşma sağlanması ve dava süreçlerinin etkin şekilde takip edilmesi konusunda da hukuki destek sunmaktayız. Tahliye taahhütnameleri ve sözleşmesel boşlukların giderilmesi gibi konularda önleyici hukuk hizmeti vererek ileride doğabilecek ihtilafların önüne geçmeyi amaçlamaktayız.",
      "Kiraya veren ve kiracıların hak ve yükümlülüklerini koruyacak şekilde, hem dava süreçlerinde hem de danışmanlık aşamasında kapsamlı hukuki hizmet sunarak kira ilişkilerinin güvenli, dengeli ve mevzuata uygun şekilde yürütülmesini sağlamaktayız. Hukuk Bürosu; başta işyeri olmak üzere, işyeri ve konut kira sözleşmeleri, alt kira sözleşmelerinin hazırlanması, mevcut sözleşme koşullarının ekonomik ve siyasi gelişmeler uyarınca piyasa koşullarına uyarlanması ve revize edilmesi, kira bedelinin tespiti, kira sözleşmesinin feshi, kira sözleşmesinden doğan alacakların tahsili ve kiralananın tahliyesi süreçlerini takip etmektedir.",
      "Gayrimenkul hukuku alanında ise yerli ve yabancı müvekkillere gayrimenkul alım, satım ve kiralama işlemleri başta olmak üzere geniş kapsamlı danışmanlık hizmeti verilmektedir. Bu kapsamda taşınmaz satış vaadi sözleşmelerinin hazırlanması ve müzakeresi, tapu kayıtlarının incelenmesi ve hukuki risk analizlerinin oluşturulması, hukuki durum tespit raporlarının hazırlanması, ipotek, üst hakkı ve intifa hakkı gibi ayni ve şahsi haklara ilişkin sözleşmelerin düzenlenmesi ile kat karşılığı inşaat sözleşmelerinin hazırlanması ve müzakeresi gibi işlemler yürütülmektedir.",
    ],
  },
  {
    title: "Miras Hukuku",
    slug: "miras-hukuku",
    paragraphs: [
      "Büromuz, gerçek ve tüzel kişilere kapsamlı danışmanlık ve temsil hizmetleri sunmaktadır.",
      "Mirasın planlanmasından paylaşımına kadar uzanan tüm süreçlerde müvekkillerin hak ve menfaatlerini korumayı, olası uyuşmazlıkları önlemeyi ve ortaya çıkan ihtilafları etkin şekilde çözmeyi hedeflemekteyiz. Bu kapsamda; vasiyetname ve miras sözleşmelerinin hazırlanması, miras planlamasının yapılması, malvarlığının gelecek nesillere hukuka uygun ve dengeli şekilde aktarılmasının sağlanması konularında müvekkillere stratejik danışmanlık sunmaktayız.",
      "Mirasın açılmasıyla birlikte ortaya çıkan hukuki süreçlerde; terekenin tespiti, mirasçılık belgesinin alınması, mirasın reddi, mirasın paylaşımı ve ortaklığın giderilmesi gibi işlemlerin her aşamasında müvekkillere destek sağlamaktayız. Mirasçılar arasında doğabilecek uyuşmazlıkların çözümünde önleyici ve uzlaşmacı yaklaşımlar benimsemekle birlikte, gerekli hallerde dava süreçlerini etkin bir şekilde takip etmekteyiz.",
      "Ulusal ve uluslararası müvekkillere hizmet veren büromuz, yabancı unsurlu miras ilişkileri, farklı ülke hukuklarının uygulanması ve sınır ötesi malvarlıklarının yönetimi konularında da danışmanlık sunmaktadır.",
    ],
  },
  {
    title: "Rekabet Hukuku",
    slug: "rekabet-hukuku",
    paragraphs: [
      "Büromuz, müvekkillerine kapsamlı, stratejik ve sonuç odaklı hukuki danışmanlık ve temsil hizmetleri sunmaktadır.",
      "Bu kapsamda; rekabeti sınırlayıcı anlaşmalar, hâkim durumun kötüye kullanılması, kartel iddiaları ve haksız rekabet uygulamaları başta olmak üzere rekabet hukukuna ilişkin tüm süreçlerde önleyici ve koruyucu hukuki destek sağlanmaktadır.",
      "Müvekkillerin faaliyetlerinin yürürlükteki mevzuata uyumlu şekilde sürdürülmesi amacıyla; birleşme ve devralma işlemlerinin rekabet hukuku boyutunun değerlendirilmesi, gerekli bildirim ve izin süreçlerinin yürütülmesi, menfi tespit ve muafiyet başvurularının hazırlanması ile sözleşmelerin rekabet kurallarına uygunluğunun denetlenmesi konularında danışmanlık verilmektedir.",
      "Rekabet Kurumu nezdinde yürütülen ön araştırma, soruşturma ve yerinde inceleme süreçlerinde müvekkilleri etkin şekilde temsil etmekte; savunma stratejilerinin oluşturulması, taahhüt süreçlerinin yönetimi ve uzlaşma mekanizmalarının değerlendirilmesi hususlarında hukuki destek sunmaktayız.",
      "Bunun yanı sıra, şirketlere özel rekabet hukuku uyum programlarının oluşturulması, iç denetim ve eğitim faaliyetlerinin yürütülmesi, mevzuat değişikliklerinin takibi ve şirket politikalarının güncellenmesi suretiyle müvekkillerin olası hukuki risklerinin en aza indirilmesi hedeflenmektedir.",
    ],
  },
  {
    title: "Sağlık ve İlaç Hukuku",
    slug: "saglik-ve-ilac-hukuku",
    paragraphs: [
      "Büromuz, ilaç, tıbbi cihaz, biyoteknoloji, takviye edici gıdalar ve yaşam bilimleri sektörlerinde faaliyet gösteren yerli ve yabancı müvekkillere kapsamlı hukuki danışmanlık hizmeti sunmaktadır.",
      "Hizmetlerimiz; regülasyon uyumu, ruhsatlandırma ve lisans süreçlerinin takibi, Sağlık Bakanlığı ve ilgili düzenleyici kurumlar nezdindeki başvuruların yürütülmesi, idari yazışmaların gerçekleştirilmesi ve mevzuat değişikliklerinin yakından izlenerek müvekkillerin bilgilendirilmesini kapsamaktadır.",
      "Ayrıca ürün yaşam döngüsünün tüm aşamalarında; Ar-Ge, klinik araştırmalar, etik kurul süreçleri, farmakovijilans yükümlülükleri, fiyatlandırma, geri ödeme ve pazar erişimi süreçlerinde hukuki destek sağlanmaktadır.",
      "Fikri mülkiyet haklarının korunması kapsamında marka, patent ve veri imtiyazı süreçleri yönetilmekte; lisans, distribütörlük, ortak girişim, teknoloji transferi ve diğer ticari sözleşmeler hazırlanmakta ve müzakere edilmektedir.",
      "Sağlık sektöründe faaliyet gösteren hastaneler, klinikler, özel sağlık kuruluşları, tıp merkezleri, laboratuvarlar ve sağlık teknolojisi şirketlerine; hasta hakları, tıbbi sorumluluk, malpraktis, ürün sorumluluğu ve idari uyuşmazlıklar dahil olmak üzere dava ve uyuşmazlık süreçlerinde temsil hizmeti verilmektedir.",
      "Uluslararası mevzuat ve karşılaştırmalı hukuk uygulamaları yakından takip edilerek, müvekkillere güncel gelişmeler doğrultusunda stratejik ve çözüm odaklı danışmanlık sunulmakta; değişen regülasyonlara hızlı uyum sağlanması için proaktif yaklaşımlar geliştirilmektedir.",
    ],
  },
  {
    title: "Sigorta Hukuku",
    slug: "sigorta-hukuku",
    paragraphs: [
      "Büromuz, sigorta sözleşmelerinden doğan uyuşmazlıkların çözümünde kapsamlı ve etkin hukuki destek sunmaktadır.",
      "Rizikonun gerçekleşip gerçekleşmediğinin tespiti, meydana gelen zararın poliçe kapsamında değerlendirilmesi, kusur oranlarının belirlenmesi ve bu hususların sözleşmeye etkilerinin incelenmesi süreçleri titizlikle yürütülmektedir. Her dosyaya özgü yaklaşım benimsenerek, hızlı ve sonuç odaklı çözümler üretilmektedir.",
      "Sigorta uyuşmazlıkları kapsamında; sigorta şirketlerine yapılacak başvurular, hasar ve tazminat taleplerinin takibi, rücu süreçlerinin yürütülmesi ile Sigorta Tahkim Komisyonu nezdindeki başvurular profesyonel şekilde gerçekleştirilmektedir. Ayrıca, asliye hukuk ve ticaret mahkemeleri başta olmak üzere yargı mercileri nezdinde açılan davalar etkin biçimde takip edilmektedir.",
      "Büromuz; kasko, trafik, sağlık, nakliyat, kredi, hayat ve sorumluluk sigortaları başta olmak üzere sigorta hukukunun farklı alanlarında hizmet sunmaktadır. Bunun yanı sıra, sigorta poliçelerinin hazırlanması, müzakeresi, feshi ve yorumlanması süreçlerinde hukuki danışmanlık verilmekte; sigorta şirketleri ile sigortalılar arasında ortaya çıkan uyuşmazlıkların en kısa sürede çözümlenmesi hedeflenmektedir.",
    ],
  },
  {
    title: "Sözleşmeler Hukuku",
    detailTitle: "Sözleşme Hukuku",
    slug: "sozlesmeler-hukuku",
    paragraphs: [
      "Büromuz, yerel ve uluslararası ölçekte, ticari ilişkilerin güvenli ve etkin şekilde yapılandırılmasını sağlamak amacıyla kapsamlı hukuki danışmanlık hizmeti sunmaktadır.",
      "Müvekkillerin ihtiyaçları doğrultusunda, ticari sözleşmelerden pay devir ve ortaklık sözleşmelerine, tedarik ve dağıtım anlaşmalarından lisans, franchise, know-how ve hizmet sözleşmelerine; kira, inşaat, finansman, yatırım ve iş ortaklığı sözleşmeleri dahil olmak üzere geniş bir yelpazede sözleşme hazırlanması, incelenmesi, müzakere edilmesi ve uygulanmasına ilişkin süreçleri yönetmekteyiz.",
      "Hizmetlerimiz, yalnızca sözleşme metinlerinin hazırlanması ile sınırlı olmayıp; taraflar arasındaki menfaat dengesinin doğru kurulması, risklerin tespit edilerek önleyici hukuki koruma sağlanması, sözleşme öncesi müzakere süreçlerinin yürütülmesi, imza ve kapanış işlemlerinin gerçekleştirilmesi, sözleşmelerin uygulanmasının takibi ile değişiklik, yenileme, fesih ve sona erme süreçlerinin yönetilmesini de kapsamaktadır.",
      "Ayrıca sözleşmelerden doğabilecek uyuşmazlıklara ilişkin çözüm süreçlerinde müvekkiller, mahkemeler ve tahkim mercileri nezdinde temsil edilmektedir. Büromuz, işletmelerin operasyonel süreçlerini kolaylaştırmak amacıyla tip sözleşme ve standart metinler de geliştirmekte; mevzuata uygun, uygulanabilir, açık ve dengeli sözleşme yapıları oluşturarak olası uyuşmazlık risklerini en aza indirmeyi hedeflemektedir.",
      "Uzman ekibimiz, yabancılık unsuru içeren ve uluslararası nitelikteki sözleşmeler dahil olmak üzere, farklı sektörlerin gereksinimlerine uygun şekilde Türkçe ve İngilizce dillerinde hizmet vermekte; sözleşmelerin hazırlanması, yorumlanması, revize edilmesi, feshi ve uyuşmazlıkların çözümü süreçlerinde etkin hukuki destek sağlamaktadır.",
    ],
  },
  {
    title: "Spor Hukuku",
    slug: "spor-hukuku",
    paragraphs: [
      "Büromuz, sporcular, spor kulüpleri, federasyonlar, menajerlik şirketleri, spor organizasyonları ve spor sektöründe faaliyet gösteren diğer tüm gerçek ve tüzel kişilere kapsamlı hukuki hizmet sunmaktadır.",
      "Bu çerçevede; spor kulüpleri ve federasyonların kuruluş, yeniden yapılanma, organizasyon ve yönetim süreçlerine ilişkin hukuki danışmanlık verilmekte, spor faaliyetlerinin yürütülmesinde ortaya çıkan her türlü uyuşmazlıkta etkin çözüm mekanizmaları geliştirilmektedir.",
      "Spor hukukuna ilişkin hizmetlerimiz; disiplin soruşturmaları ve ihlalleri, sözleşmesel uyuşmazlıklar, transfer işlemleri, lisanslama süreçleri, tazminat talepleri ve mali ihtilaflar gibi geniş bir yelpazeyi kapsamaktadır. Ayrıca sponsorluk, reklam, yayın hakları, isim ve imaj hakları, forma ve ürün reklamları ile ticari iş birliklerine ilişkin sözleşmeler de hizmet alanımız içerisindedir.",
      "Spor faaliyetlerinden doğan uyuşmazlıklar kapsamında; Türkiye Futbol Federasyonu, ilgili spor federasyonları, idari ve adli yargı mercileri ile uluslararası spor yargı organları nezdinde temsil hizmeti verilmektedir. Özellikle Spor Tahkim Mahkemesi (CAS) başta olmak üzere ulusal ve uluslararası spor yargı mercilerinde müvekkiller etkin şekilde temsil edilmektedir.",
      "Ekibimiz, spor hukukundan doğan her türlü uyuşmazlıkta, ulusal ve uluslararası yargı mercileri ile tahkim kurumları nezdinde temsil ve danışmanlık hizmeti vermekte; müvekkillerin hak ve menfaatlerini etkin, sistematik ve mevzuata uygun şekilde korumayı amaçlamaktadır.",
    ],
  },
  {
    title: "Şirketler ve Ticaret Hukuku",
    slug: "sirketler-ve-ticaret-hukuku",
    paragraphs: [
      "Büromuz, yerli ve yabancı sermayeli şirketlere kuruluş aşamasından tasfiye sürecine kadar uzanan tüm kurumsal yaşam döngüsü boyunca kapsamlı danışmanlık hizmetleri sunmaktadır. Müvekkillerin faaliyetlerinin mevzuata uyumlu, etkin ve sürdürülebilir şekilde yürütülmesini temel yaklaşım olarak benimsemekteyiz.",
      "Bu kapsamda şirket kuruluşları, şube ve irtibat bürosu açılışları, esas sözleşmelerin hazırlanması ve tadili, sermaye artırımı ve azaltımı, birleşme ve devralmalar, tür değişikliği, yeniden yapılandırma ve tasfiye işlemlerine ilişkin tüm süreçlerde hukuki destek sağlanmaktadır.",
      "Büromuz, ticari sözleşmelerin hazırlanması, incelenmesi ve müzakere edilmesi süreçlerinde etkin rol almaktadır. Pay sahipleri sözleşmeleri, ortak girişim anlaşmaları, hisse devir sözleşmeleri, lisans, distribütörlük, franchise, tedarik ve hizmet sözleşmeleri dahil olmak üzere geniş bir sözleşme yelpazesinde hizmet sunulmaktadır.",
      "Birleşme ve devralma işlemlerinde; hukuki durum tespiti, sözleşme müzakereleri, işlem dokümantasyonu ve kapanış süreçleri dahil olmak üzere uçtan uca hukuki destek sağlanmaktadır. Bunun yanı sıra finansal yeniden yapılandırma, teminat mekanizmaları, rehin ve ipotek işlemleri gibi ticari işlemler de hizmet kapsamımızdadır.",
      "Ticari uyuşmazlıkların çözümünde dava, arabuluculuk ve ulusal/uluslararası tahkim süreçlerinde etkin temsil hizmeti sunulmaktadır. Ortaklık ihtilafları, sözleşme ihlalleri, haksız rekabet ve yönetici sorumluluğuna ilişkin uyuşmazlıklar bu kapsamda ele alınmaktadır.",
      "Uluslararası ticaret hukuku alanında ise yabancı sermayeli şirketlerin Türkiye yapılanmaları, Türk şirketlerinin yurt dışı yatırımları, sınır ötesi ticari sözleşmeler ve uyum süreçlerine ilişkin danışmanlık hizmeti verilmektedir.",
    ],
  },
  {
    title: "Taşımacılık ve Lojistik Hukuku",
    slug: "tasimacilik-ve-lojistik-hukuku",
    paragraphs: [
      "Büromuz, kara, deniz, hava ve demiryolu taşımacılığı ile lojistik sektörüne ilişkin her türlü hukuki uyuşmazlık, danışmanlık ve uyum ihtiyacına yönelik olarak yerli ve yabancı müvekkillere kapsamlı hukuki hizmet sunmaktadır.",
      "Hizmetlerimiz; taşıma sözleşmelerinin hazırlanması ve müzakeresi, çarter, navlun ve lojistik sözleşmeleri, konşimento ve taşıma belgeleri, taşıyan–taşıtan ilişkileri, CMR kapsamındaki sorumluluklar, yük hasarı ve zıyaı, gecikme ve tazminat talepleri, sigorta ve reasürans uyuşmazlıkları, gemi, uçak ve kara taşıtları sigortalarına ilişkin ihtilaflar ile müşterek avarya, çatma, kurtarma ve yardım gibi deniz ticaretine özgü uyuşmazlıkları kapsamaktadır.",
      "Deniz taşımacılığı alanında; gemi inşa sözleşmeleri, gemi alım-satımı ve finansmanı, ipotek ve teminat yapıları, H&M ve P&I sigortaları, gemi alıkoyma işlemleri, deniz kirliliği, enkaz kaldırma, liman ve gümrük işlemleri ile uluslararası deniz ticareti kuralları çerçevesinde ortaya çıkan tüm ihtilaflar konusunda danışmanlık ve dava takibi hizmeti sunulmaktadır.",
      "Havacılık ve kara taşımacılığı kapsamında ise; uluslararası ve ulusal taşımalar, intermodal ve kombine taşımacılık, hızlı kargo ve lojistik operasyonlar, filo yönetimi, taşıma organizasyonları ve bu faaliyetlerden doğan her türlü sorumluluk ve tazminat uyuşmazlığı alanlarında hukuki danışmanlık verilmektedir.",
      "Büromuz ayrıca, taşımacılık ve lojistik sektöründe birleşme ve devralma işlemleri, proje finansmanı, sözleşme yapıları, risk dağılımı ve regülasyon uyumu konularında stratejik danışmanlık sunmaktadır.",
      "Uyuşmazlık çözümü alanında büromuz; Türk mahkemeleri, tahkim mercileri ve uluslararası yargı organları nezdinde müvekkillerini temsil etmekte, ICC, LMAA ve benzeri tahkim merkezleri dahil olmak üzere uluslararası platformlarda etkin savunma ve takip hizmeti sunmaktadır.",
      "Hizmet anlayışımız; akademik destek, sektör deneyimi ve güncel mevzuat takibi ile güçlendirilmiş olup, yerli ve yabancı müvekkillerin ihtiyaçlarına uygun, çözüm odaklı ve sürdürülebilir hukuki danışmanlık yaklaşımı çerçevesinde yürütülmektedir.",
    ],
  },
  {
    title: "Tüketici Hukuku",
    slug: "tuketici-hukuku",
    paragraphs: [
      "Büromuz, hem satıcı ve hizmet sağlayıcı konumundaki işletmelere hem de tüketicilere kapsamlı danışmanlık ve temsil hizmetleri sunmaktadır.",
      "Tüketici sözleşmelerinin hazırlanması ve revizyonu, mesafeli satış ve abonelik süreçlerinin yapılandırılması, garanti ve satış sonrası hizmetlerin düzenlenmesi ile reklam ve ticari uygulamaların mevzuata uygunluğunun denetlenmesi konularında müşteri ilişkilerinin yönetimi dahil olmak üzere ticari faaliyetlerin tüm aşamalarında müvekkillere destek sağlamaktayız.",
      "Şirketlere yönelik olarak, tüketici mevzuatına uyum süreçlerinin oluşturulması, müşteri ilişkilerinin hukuki çerçevede yönetilmesi, bayi ve distribütörlük ağlarının düzenlenmesi ve olası risklerin önceden tespitine yönelik önleyici hukuki danışmanlık hizmetleri sunulmaktadır.",
      "Tüketiciler bakımından ise ayıplı mal ve hizmetlerden kaynaklanan uyuşmazlıklar başta olmak üzere; iade, değişim, bedel indirimi ve tazminat taleplerine ilişkin başvuru süreçlerinin yürütülmesi, Tüketici Hakem Heyetleri ve tüketici mahkemeleri nezdinde temsil ve uyuşmazlıkların çözümü konularında hukuki destek sunmaktayız.",
      "Büromuz, tüketici hukukundan kaynaklanan ihtilaflarda arabuluculuk ve dava süreçlerini etkin şekilde yönetirken, müvekkillerinin ticari itibarını koruyan, hızlı ve sonuç odaklı çözümler geliştirmeyi esas almaktadır.",
    ],
  },
  {
    title: "Yabancılar ve Vatandaşlık Hukuku",
    slug: "yabancilar-ve-vatandaslik-hukuku",
    paragraphs: [
      "Büromuz, Türkiye’de ikamet etmek, çalışmak, yatırım gerçekleştirmek veya Türk vatandaşlığına başvurmak isteyen yabancı uyruklu gerçek kişiler ile yatırımcılara kapsamlı hukuki danışmanlık ve avukatlık hizmetleri sunmaktadır.",
      "5901 sayılı Türk Vatandaşlığı Kanunu ve ilgili mevzuat hükümleri çerçevesinde; ikamet yoluyla vatandaşlık, evlilik yoluyla vatandaşlık ve yatırım yoluyla vatandaşlık başta olmak üzere tüm vatandaşlık kazanım yolları profesyonel bir yaklaşım ile ele alınmakta, her bir başvuru türüne özgü idari ve hukuki süreçler titizlikle yürütülmektedir.",
      "Büromuz, vatandaşlık başvurularının yanı sıra ikamet izni, çalışma izni, aile ikamet izni ile bu izinlerin uzatma ve yenileme işlemlerini de kapsamlı şekilde yürütmektedir. Yabancı gerçek ve tüzel kişilerin Türkiye’deki tüm idari süreçleri; ilgili kamu kurum ve kuruluşları nezdinde başvuruların yapılması, takibi ve sonuçlandırılması aşamalarını içerecek şekilde eksiksiz olarak yönetilmektedir.",
      "Uluslararası göç ve vatandaşlık hukuku alanındaki uzmanlığımız doğrultusunda, Golden Visa ve benzeri yatırım temelli oturum ve vatandaşlık programlarına ilişkin hukuki danışmanlık hizmetleri de sunulmaktadır. Bu kapsamda farklı ülkelerde uygulanan programların hukuki şartları, yatırım kriterleri ve başvuru prosedürleri değerlendirilmekte; müvekkillerin ihtiyaç ve hedefleri doğrultusunda en uygun hukuki strateji belirlenmektedir.",
      "Büromuz, bireysel müvekkillerin yanı sıra kurumsal yatırımcılara da hizmet sunmak suretiyle, Türkiye’de uzun vadeli yerleşim, yatırım ve vatandaşlık planlamalarına yönelik bütüncül ve stratejik çözümler geliştirmektedir.",
    ],
  },
];

export const lawyer = {
  name: "Av. Oğulcan İNEN",
  cardName: "Oğulcan İnen",
  role: "Kurucu ve Yönetici Ortak",
  email: "ogulcaninen@gmail.com",
  mobile: "+90 533 376 2365",
  officePhone: "+90 533 376 2365",
  education: "Özyeğin Üniversitesi, Hukuk Fakültesi - Lisans",
  languages: "İngilizce, Türkçe",
  bar: "Ankara 1 nolu Barosu, Türkiye Barolar Birliği",
  image: "/ogulcan_inen.jpeg",
};
